import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		int numOffamilies = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
        Random generator = new Random(seed);  
		int count = 0;
		double average = 1;
		int twoChild = 0;
		int threeChild = 0;
		int fourplusChild = 0;
		double rand = generator.nextDouble();
		for(int i = 1; i <= numOffamilies; i++)
		{
			rand = generator.nextDouble();
			count = 1;
			if(rand < 0.5)
			{
				rand = generator.nextDouble();
				while(rand < 0.5)
				{
					rand = generator.nextDouble();
					count = count + 1;
				}
				count = count + 1;
			}
			else
			{
				rand = generator.nextDouble();
				while(rand > 0.5)
				{
					rand = generator.nextDouble();
					count = count + 1;
				}
				count = count + 1;
			}
			if(count == 2)
				twoChild = twoChild + 1;
			if(count == 3)
				threeChild = threeChild + 1;
			if(count >= 4)
				fourplusChild = fourplusChild + 1;
			average = average + count;
		}
		String common;
		if(twoChild > threeChild){
			if(twoChild > fourplusChild){
				common = "2.";}
			else{
			common = "4 or more.";}
		}
		else{
			if(threeChild > fourplusChild){
				common = "3.";}
			else{
				common = "4 or more.";}
			}
		System.out.println("Average: " + average/numOffamilies + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + twoChild);
		System.out.println("Number of families with 3 children: " + threeChild);
		System.out.println("Number of families with 4 children: " + fourplusChild);
		System.out.println("The most common number of children is " + common);   
	}
}
